### ISSUE TITLE
Would be helpful to include extensions like Dockerfile, .toml, and .dockerignore

### ISSUE THREAD

**Issue by connorjchen** [bevry/textextensions#238]
PR: https://github.com/bevry/textextensions/pull/239

**Comment by balupton** [comment]
Merged so available on the next tag. Will do a proper release tomorrow.

**Comment by balupton** [comment]
Released to v5.16.0 once this build passes https://github.com/bevry/textextensions/actions/runs/4832964714

**Comment by balupton** [comment]
The backers section will be updated sometime in the coming months once I sort out my automated [boundation](https://github.com/bevry/boundation) workflow once again
